// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RewindAPI.Data;

#nullable disable

namespace RewindAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610163440_AddMediaAndCollection")]
    partial class AddMediaAndCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RewindAPI.Models.BookDetails", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Isbn")
                        .HasColumnType("text")
                        .HasColumnName("isbn");

                    b.Property<int?>("Pages")
                        .HasColumnType("integer")
                        .HasColumnName("pages");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.HasKey("MediaItemId");

                    b.ToTable("book_details");
                });

            modelBuilder.Entity("RewindAPI.Models.CollectionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_item_id");

                    b.Property<string>("PlatformPlayed")
                        .HasColumnType("text")
                        .HasColumnName("platform_played");

                    b.Property<string>("Review")
                        .HasColumnType("text")
                        .HasColumnName("review");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("user_collection");
                });

            modelBuilder.Entity("RewindAPI.Models.GameDetails", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Developer")
                        .HasColumnType("text")
                        .HasColumnName("developer");

                    b.PrimitiveCollection<string[]>("Platforms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("platforms");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.HasKey("MediaItemId");

                    b.ToTable("game_details");
                });

            modelBuilder.Entity("RewindAPI.Models.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("Type");

                    b.ToTable("media_items");
                });

            modelBuilder.Entity("RewindAPI.Models.MovieDetails", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Director")
                        .HasColumnType("text")
                        .HasColumnName("director");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text")
                        .HasColumnName("original_language");

                    b.HasKey("MediaItemId");

                    b.ToTable("movie_details");
                });

            modelBuilder.Entity("RewindAPI.Models.SeriesDetails", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Creator")
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<string>("SeriesStatus")
                        .HasColumnType("text")
                        .HasColumnName("series_status");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("total_episodes");

                    b.Property<int?>("TotalSeasons")
                        .HasColumnType("integer")
                        .HasColumnName("total_seasons");

                    b.HasKey("MediaItemId");

                    b.ToTable("series_details");
                });

            modelBuilder.Entity("RewindAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("RewindAPI.Models.BookDetails", b =>
                {
                    b.HasOne("RewindAPI.Models.MediaItem", "MediaItem")
                        .WithOne("BookDetails")
                        .HasForeignKey("RewindAPI.Models.BookDetails", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("RewindAPI.Models.CollectionEntry", b =>
                {
                    b.HasOne("RewindAPI.Models.MediaItem", "MediaItem")
                        .WithMany("CollectionEntries")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RewindAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RewindAPI.Models.GameDetails", b =>
                {
                    b.HasOne("RewindAPI.Models.MediaItem", "MediaItem")
                        .WithOne("GameDetails")
                        .HasForeignKey("RewindAPI.Models.GameDetails", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("RewindAPI.Models.MovieDetails", b =>
                {
                    b.HasOne("RewindAPI.Models.MediaItem", "MediaItem")
                        .WithOne("MovieDetails")
                        .HasForeignKey("RewindAPI.Models.MovieDetails", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("RewindAPI.Models.SeriesDetails", b =>
                {
                    b.HasOne("RewindAPI.Models.MediaItem", "MediaItem")
                        .WithOne("SeriesDetails")
                        .HasForeignKey("RewindAPI.Models.SeriesDetails", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("RewindAPI.Models.MediaItem", b =>
                {
                    b.Navigation("BookDetails");

                    b.Navigation("CollectionEntries");

                    b.Navigation("GameDetails");

                    b.Navigation("MovieDetails");

                    b.Navigation("SeriesDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
